### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by szappanyos** [Neonox31/node-red-contrib-zigate#1]
Could you write an example of usage? 
I haven't been able to figure it out on my own.
I tried different ways to send the command, but it failed.

**Comment by szappanyos** [comment]
Browsing through the code I have found out that only two commands are supported:
PermitJoin = 0x0049
GetDevicesList = 0x0015

**Comment by Neonox31** [comment]
Sorry for being late...
As you say, there is only two supported commands now.
I'll try to find time to implement more commands and write an example for each.

What particular command is missing for you @szappanyos ?

**Comment by szappanyos** [comment]
I was trying get version command just to see if everything works, but it is not necessary anymore.
If I have time I will try to add a node for Ikea Tradfri.

**Comment by Neonox31** [comment]
OK, i'll try to be more reactive next time.
Thanks, Ikea Tradfri is very welcomed !!

**Comment by gege888** [comment]
Hi,
A year later but same request ;-)
I'm able to insert nodes but no idea on how to use them... How can we send a simple PermitJoin (yeah I know it's 0x0049 but cannot manage to set it in the node itself, always receive "Error: Unsupported command code : NaN").
Next would be to send arbitrary commands to any registered device, do you think it's achievable with the output node ? (e.g. manually crafting the on/off code of some devices).
Many thx for your help!

Update : seems it has to be 0x0049 in the topic field of inject node.  Now receive status 128 in packet type 73... need to investigate. Other part of the question still valid though ;-)

**Comment by Neonox31** [comment]
Hi @gege888,

I just pushed a new branch (https://github.com/Neonox31/node-red-contrib-zigate/tree/doc-add-getting-started-guide) with a basic `README.md` file detailling how to get started.
Let me know if this guide helps you enough or if more details should be mentionned.

**Comment by gege888** [comment]
Thx Neonox for your quick answer!

1) readme : This is a good start ;-) I think `DEBUG='zigate*' node-red ` tip would deserve a small decription as well, to better understand what's happening Under the Hood.

2) feature request : I see extension supports 2 commands today (because it takes time to prepare them with default values, validate params etc), but I'm still trying to understand if we could send arbitrary 'raw' commands to zigate by specifying all the low level fields as listed here https://zigate.fr/wiki/commandes-zigate  (i.e. specify command and params, just letting your tool computing hash and assembling parts). For example I may specify something as hex string like {"raw":"FFFC1E00"} in a join payload instead of using {"interval":30}. This would allow anyone generating "not yet supported" commands like getVersion, setLed etc. 
node-red extension would assemble 0x01 + topic + {LEN of raw field /2} + {computed CKS} + Raw field as bin + 0x03

What do you think ?
Cheers!
